version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  controller:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - app-network
  
  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    depends_on:
      - controller
    ports:
      - "8501:8501"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge